In [ ]:
import numpy as np

In [3]:
a = np.array([[1,6],
            [2,8],
            [3,11],
            [3,10],
            [1,7]])

In [4]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [5]:
a.shape

(5, 2)

In [6]:
a.size

10

In [7]:
mean_a = a.mean(axis = 0)

In [8]:
mean_a

array([2. , 8.4])

In [9]:
print(mean_a)

[2.  8.4]


ex_2

In [13]:
a_centered = a - mean_a
print(a_centered)

[[-1.  -2.4]
 [ 0.  -0.4]
 [ 1.   2.6]
 [ 1.   1.6]
 [-1.  -1.4]]


ex_3

In [12]:
a_centered_sp = a_centered.T[0] @ a_centered.T[1]
print(a_centered_sp)

8.0


In [14]:
print(a_centered_sp / (a_centered.shape[0] - 1))

2.0


ex_4

In [15]:
print(np.cov(a.T)[0, 1])

2.0


Pandas
ex_1

In [16]:
import pandas as pd

In [17]:
authors = pd.DataFrame({"author_id":[1, 2, 3], 
                        "author_name":['Тургенев', 'Чехов', 'Островский']})
print(authors)

   author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский


In [18]:
book = pd.DataFrame({"author_id":[1, 1, 1, 2, 2, 3, 3], 
                     "book_title":['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'], 
                     "price":[450, 300, 350, 500, 450, 370, 290]})
print(book)

   author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290


ex_2

In [20]:
authors_price = pd.merge(authors, book, on = 'author_id', how = 'outer')
print(authors_price)

   author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290


ex_3

In [21]:
top5 = authors_price.nlargest(5, 'price')
print(top5)

   author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350


ex_4

In [35]:
authors_stat = authors_price.groupby('author_name').agg({'price':['min', 'max', 'mean']})
authors_stat = authors_stat.rename(columns={'min':'min_price', 'max':'max_price', 'mean':'mean_price'})
print(authors_stat)

                price                      
            min_price max_price  mean_price
author_name                                
Островский        290       370  330.000000
Тургенев          300       450  366.666667
Чехов             450       500  475.000000
